#!/bin/bash
# This goes in /usr/bin/tradr-shell
# User shell that is restricted
allowed_commands=("ls" "cat" "echo" "docker" "whoami" "pwd" "cli" "cd")

# Extract the command (first word)
command=$(echo "$1" | awk '{print $1}')

echo "This is a restricted shell"

# Display the entered command
echo "Command entered: $@"

# Check if the command is in the allowed list
if [[ " ${allowed_commands[@]} " =~ " $command " ]]; then
    # Execute the command
    $@
else
    # Reject the command if not allowed
    echo "Command not allowed."
fi

