#!/usr/bin/expect
# Install Osiris Agent

set force_conservative 1  ;     # set to 1 to force conservative mode even if
                          ;     # script wasn't run conservatively originally
if {$force_conservative} {
    set send_slow {1 .1}
    proc send {ignore arg} {
        sleep .1
        exp_send -s -- $arg
    }
}

set timeout -1

spawn ./install.sh
match_max 100000

expect "Continue with installation"
send -- "y\r"

expect "Install osiris agent"
send -- "y\r"

expect "Installation directory for binaries"
send -- "y\r"

expect "Start scan agent now"
send -- "y\r"

expect eof
